travis:
  secure:
    BINSTAR_TOKEN: vY5/bcoFmcrqTIdg2RfeL3vv1z1oQnTfTIA9vt0c7NtZ7iqo+VmWi2apHEx1jVRxkGX4p81A4v4H46cxm+ujwK+OUxn56cMa3MSiwnWqHbN1lFmkESyZRPN/ovqsyEcWUBxrCRLjwrnAGmHxGvLuu9Qr5BIFn7l06NdsrRCt0yBB7sajTO6Dwu7xsaSkGVvyzcAMPHLDLWttDoz1aH1mCg6ddVt9iVtTB0hJT32xfcvZFtIrCh4LpIQReQVND93kd+FePcXFyrtb/GvYKYx+7lY8tY1JYhqI4QZu9lcUJDjHw0UZ9mox4/nywuHG375jpxxqMeGkAqRiUCUOtjq7P0KafnGix4D1zxV1ySz4SgjKu/g/Q6VoRYKm+dJ5fh46FbKpltspPyFKz/3vkcIg10CDAL9t9CRoGcbZTr478MAY0t7+tHMGWJj4uVOeonsbBl1fKadzMYaDV7elGBWtHWCXdxGERhEBgdVu9AoLHl0w5AVYycVKo9PT/W0rgiyGqE/D67JzhsmVc5NHFXpO1KRfCiZpq473bcR2q3hEfq0DIlXf8gD3WBTRr5JNyE1XBJPRZA1c7jSq0No0cZNUZqgOfaKXxyICpznPyWJtQdsy/5DBeRhkZUlP7KjZYh08OUklcUQeXL8Fc2E+SQoDD1afiE9ZTGVVod9eIkZOv3Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
