travis:
  secure:
    BINSTAR_TOKEN: TldKD8ULsg6aMPP1N7IYEj+DDHZh8B0J6ap0OqeubpcYYiieN8c6tXjI9nB75IPzjc6N8Q4zbSt+tGLWNDYRHN7g7YK/6LnPybbg4Pg0/FE+Y6BWmudFV6zQR7B1zUeh2AT/gE/Ijk32pfJ3x2gBlrTeNtlpSWdxuo/6GUZQkaYmWVFatBAgB4x8jH5IIINa30EQelIOiZJDZ820bnpZsS4fSV8bdpeomwWwOv2ONfFXQOfGAYKqDBLvQkJ7Aqj8W+dfDWCZ9uJdwAksPfuZC7aarPzV/Qsg3H5vtEq8xacuIvxC84COFXib0tvHkj+GqtBgNjcj834c9cLucGiZTFr8jKQgmXwQU5+sJwZrMh/OF6U252qig5IeALXQAXntIJYVvzXlJSSxhjGLVdJQCsaywE2IBlonjDVDoj3BtM/IgGO0eIoImmjSKwrLvg2gZBS4WHQkLL8dq1rzShSV+4yPPtXvg2wvSv3Hev64CRajiBSeTpa4CjFPr7MPVDC3Bj48jnPNgLUd43/M0v00wzcExpxQhJuxcqetxv88qhWHUAA+wL+DzlnOr218nQOi4BqcmKRuiRH5ikmm4eSiSvV00+ufr1Et58BTSWKa6xa3JrzP9Y4wqSRtEg+S88OfT2McFvLNhiil/92p+JzFzkSyt873cznTqARGIX0uxi4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
